spring:
  application:
    name: bili-comment-crawler

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db?useSSL=false&serverTimezone=UTC
    username: root
    password: thisisweakbutidontmind
  jpa:
    hibernate:
      ddl-auto: update
